import type { Metadata } from "next";
import { Fustat } from "next/font/google";

import "./globals.css";

const fustat = Fustat({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${fustat.className} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}